
- name: List installed php7 packages
  shell: dpkg -l | grep php7 | awk '{print $2}'
  register: installed_packages

- name: Make sure no php7 packages are installed
  apt: name={{ item }} state=absent
  with_items: "{{ installed_packages.stdout_lines }}"

- apt: name=software-properties-common

- name: Add ppa for php5 packages
  apt_repository: repo=ppa:ondrej/php

- name: Installing php packages
  apt: name={{ item }} update_cache=yes state=latest
  with_items:
    - php5.6
    - php5.6-cli
    - php5.6-mysql
    - php5.6-xml
    - imagemagick
    - unzip

- name: Installing mysql packages
  apt: name={{ item }} update_cache=yes force=yes
  with_items:
    - mysql-server-5.7
    - libmysqlclient-dev

- name: Removing apache php7 package
  apt: name=libapache2-mod-php7.0 state=absent

- name: Installing apache package
  apt: name={{ item }} update_cache=yes state=latest
  with_items:
    - apache2
    - libapache2-mod-php5.6

- name: Installing nginx
  apt: pkg=nginx state=present update_cache=yes

- name: Installing pip
  apt: name=python-pip

- name: Installing the Python MySQLB module  # Requirement for mysql_db and mysql_user
  pip: name=MySQL-python

- name: Configuring sql_mode
  blockinfile:
    path: /etc/mysql/my.cnf
    content: |
      [mysqld]
      sql_mode = "STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
  register: mysql_conf

- name: Restart mysql if necessary
  service: name=mysql state=restarted
  when: mysql_conf.changed

- name: Creating mysql database
  mysql_db: name={{ ctp_db_name }} state=present

- name: Creating mysql user
  mysql_user:
    name: "{{ ctp_db_username }}"
    password: "{{ ctp_db_password }}"
    priv: "{{ ctp_db_name }}.*:ALL"
    host: localhost
    state: present

- name: Check if ctp directory already exists
  stat: path={{ ctp_base_dir }}
  register: ctp_directory

- include: phpbb.yml
  when: not ctp_directory.stat.exists

- name: Copy nginx conf
  template:
    src=templates/ctp_reverse_proxy.conf
    dest=/etc/nginx/sites-enabled/ctp_reverse_proxy.conf

- name: Restart nginx
  service: name=nginx state=restarted

- name: Apache should listen on port 8080
  lineinfile:
    path=/etc/apache2/ports.conf
    regexp="^Listen "
    line="Listen 8080"

- name: Copy apache conf
  template:
    src=templates/ctp.conf
    dest=/etc/apache2/sites-enabled/ctp.conf
    mode=0644

- name: Add robots.txt
  copy:
    src=files/robots.txt
    dest={{ ctp_base_dir }}
    owner=www-data
    group=www-data

- name: Restart apache
  service: name=apache2 state=restarted
